# Generated by Django 5.0.3 on 2024-03-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_tag', models.CharField(help_text='Input tag with which the spider will scrape memes.', max_length=100)),
                ('img_url', models.CharField(help_text='Source URL of the meme. (ends with .jpg, .png, etc.)', max_length=400)),
                ('local_path', models.CharField(default=None, help_text='Path where the meme is stored on the server.', max_length=200, null=True)),
                ('checksum', models.CharField(default=None, help_text='Checksum of the meme image.', max_length=32, null=True)),
                ('status', models.CharField(choices=[('downloaded', 'File was downloaded'), ('uptodate', 'File was not downloaded, as it was downloaded recently, according to the file expiration policy'), ('cached', 'File was already scheduled for download, by another item sharing the same file')], help_text='Scraping status of the meme image.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='meme',
            constraint=models.UniqueConstraint(fields=('checksum',), name='unique_checksum'),
        ),
    ]
