# Generated by Django 5.0.3 on 2024-03-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CricbuzzNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news_id",
                    models.CharField(
                        default=None,
                        help_text="Id of the News Article",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "news_url",
                    models.CharField(
                        help_text="Source URL of the News Article.", max_length=400
                    ),
                ),
                ("news_title", models.TextField()),
                ("news_description", models.TextField()),
                ("news_summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "news_category",
                    models.CharField(
                        help_text="Category of the News Item", max_length=100
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="HindustanTimesNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news_id",
                    models.CharField(
                        default=None,
                        help_text="Id of the News Article",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "news_url",
                    models.CharField(
                        help_text="Source URL of the News Article.", max_length=400
                    ),
                ),
                ("news_title", models.TextField()),
                ("news_description", models.TextField()),
                ("news_summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.AddConstraint(
            model_name="cricbuzznews",
            constraint=models.UniqueConstraint(
                fields=("news_id",), name="unique_newsid_cricbuzz"
            ),
        ),
        migrations.AddConstraint(
            model_name="hindustantimesnews",
            constraint=models.UniqueConstraint(
                fields=("news_id",), name="unique_newsid_hindustan"
            ),
        ),
    ]
