# Generated by Django 5.0.3 on 2024-03-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0002_cricbuzznews_hindustantimesnews_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_id", models.CharField(default=None, max_length=32, null=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("summary", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CB", "Cricbuzz news"),
                            ("HT", "Hindustan Times news"),
                        ],
                        max_length=255,
                    ),
                ),
                ("url", models.URLField(max_length=400)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("published_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="newsarticle",
            constraint=models.UniqueConstraint(
                fields=("news_id",), name="unique_newsid"
            ),
        ),
    ]
