# Generated by Django 5.0.3 on 2024-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0003_newsarticle_newsarticle_unique_newsid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="newsarticle", name="title", field=models.TextField(blank=True),
        ),
    ]
