# Generated by Django 5.0.3 on 2024-03-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0004_alter_newsarticle_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="published_at",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
