# Generated by Django 5.0.3 on 2024-03-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0005_alter_newsarticle_published_at"),
    ]

    operations = [
        migrations.DeleteModel(name="CricbuzzNews",),
        migrations.DeleteModel(name="HindustanTimesNews",),
    ]
