# Generated by Django 5.0.4 on 2024-04-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_alter_newsarticle_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='summary_hindi',
            field=models.TextField(blank=True),
        ),
    ]
