# Generated by Django 5.0.4 on 2024-04-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_newsarticle_summary_hindi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='summary_hindi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
