# Generated by Django 5.0.4 on 2024-04-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_alter_newsarticle_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(default=None, max_length=32, null=True)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('summary_hindi', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('IPLT20', 'IPL official website')], max_length=255)),
                ('url', models.URLField(max_length=400)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('match_no', models.IntegerField(null=True)),
                ('published_at', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='matchreport',
            constraint=models.UniqueConstraint(fields=('report_id',), name='unique_reportid'),
        ),
    ]
